# Docker build and push pipeline
trigger:
- main # Trigger pipeline on push to the main branch

pool:
  name: 'Self-Hosted-Pool' # Self-hosted pool name

steps:
- task: Docker@2
  displayName: Build and Push Docker Image
  inputs:
    containerRegistry: 'Docker_HUB'
    repository: 'poornima1911/python-sample-vscode-flask-tutorial' # Docker repository
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
